config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root :to => 'products#index'

  resources :users do

  end

  resources :products do
      resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
  has_many :reviews
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_permission, only: :edit

  before_action :only => [:edit] do
    redirect_to product_path unless is_admin?
  end

  def require_permission
    if current_user != Product.find(params[:id]).user
      redirect_to root_path
    else
      @product = Product.find(params[:id])
      render :edit
    end
  end
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
    flash[:notice] = "Product successfully added!"
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Product successfully removed!"
      redirect_to products_path
    end
  end

private
  def product_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:product).permit(:name, :description, :price, :user_id)
  end
end

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
<%= f.label :name %>
<br>
<%= f.text_field :name %>
<br>
<%= f.label :description %>
<br>
<%= f.text_field :description %>
<br>
<%= f.label :price %>
<br>
<%= f.text_field :price %>
<%= f.hidden_field(:user_id, :value => current_user.id) %>
<br>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

<hr>

<% if is_admin? %>
<%= link_to "New Product", new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<br><br>
<div class="panel panel-info">
  <div class="panel-heading"><%= @product.name %></div>
  <div class="panel-body">Description: <%= @product.description %></div>
  <div class="panel-body">Price: $<%= @product.price %></div>
</div>


<br>
<br>
<h2>User Reviews</h2>
<% if is_admin? %>
  <% @product.reviews.each do |review| %>
    <p><%= review.content %> | <%= link_to "Delete", product_review_path(@product, review), method: "delete" %></p>
<% end %>

<% else %>
  <% @product.reviews.each do |review| %>
    <p><%= review.content %></p>
<% end %>
<% end %>
<span class="btn waves-effect waves-orange"><%= link_to "Leave a review", new_product_review_path(@product) %></span>

<% if is_admin? %>
<p class="btn waves-effect waves-orange"><%= link_to "Edit", edit_product_path(@product) %></p>
<p class="btn waves-effect waves-orange"><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<% end %>
<br><br>
<p class="btn waves-effect waves-orange"><%= link_to "Return to products", products_path %></p>